name: epidive-cpu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip>=23
  - numpy=1.26
  - libblas=*=*openblas
  - pandas=2.2
  - scipy>=1.11,<2
  - numba>=0.59,<0.62
  - joblib
  - threadpoolctl
  - tqdm
  - pyarrow>=14
  - polars>=0.20
  - matplotlib>=3.8
  - seaborn>=0.13
  - pip:
      - .
